### ISSUE TITLE
Make natively compatible with Unity

### ISSUE THREAD

**Issue by ThomasBartanen** [caesuric/mountain-goap#2]
It seems that this uses C#10 features, which are incompatible with Unity without workarounds (I assume, but I can't find any that would work for me).
The most recent version of Unity (2023.2) through version 2021.2 use C#9. So unless you find an absolutely necessary reason for using C#10, I would recommend using 9 (Or, if you DO know a workaround, could you put that in the readme?). Of course I understand this is meant to work with more than just Unity, so that may not be your focus.

I'm in the process of removing things like global usings (and replacing them in each file) in order to use it within Unity. I can do a pull request when I'm done if you want.

**Comment by caesuric** [comment]
Thank you for checking out the project and identifying this issue! I could have sworn that this worked in Unity for me without additional configuration when I tested it, but I may be mistaken. I already downgraded the version of .NET used once for compatibility with Unity. May I ask how you are using the library in Unity? The DLLs should work whereas the C# source files may not.

Please feel free to submit a PR if you are already making the changes, and I will happily accept it if it increases compatibility. If you will not get to it, I will look into it as well.

Thank you again!

**Comment by ThomasBartanen** [comment]
I should add the caveat that I've only worked within the Unity environment so far, so it's entirely possible I just messed things up!

I downloaded the code (version .62, but I see there is another now), and copied it into my unity assets folder. So I guess I would be using the C# files directly. I immediately got 21 errors (iirc), most to do with usings, and one to do with serilog, which I didn't have

**Comment by ThomasBartanen** [comment]
Here is what I did 
#3 

That and deleting the global usings and crossing my fingers it isn't auto-generated again hahah

Also, thank you so much for your work! It's been very helpful so far. I struggled with ReGoap, OpenGoap, and a couple others. This fits my existing code much more cleanly.

**Comment by caesuric** [comment]
> I should add the caveat that I've only worked within the Unity environment so far, so it's entirely possible I just messed things up!
> 
> I downloaded the code (version .62, but I see there is another now), and copied it into my unity assets folder. So I guess I would be using the C# files directly. I immediately got 21 errors (iirc), most to do with usings, and one to do with serilog, which I didn't have

Ah, so the tested workflow is copying the DLL (and associated files) from the ZIP release into your project and using the DLL directly. Never tried copying the C# files into Unity before, not at all surprised that doesn't work. The compiled DLL version uses a version of .NET that should be compatible with Unity. ([.NET Standard](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0))

The default logger is also not included in the base DLL package so you shouldn't have issues with Serilog when using the DLL. You can also resolve those when using the C# files directly in Unity by deleting the default logger from your local files (or by pulling Serilog into your project).

That said, this is probably a common use case for people that want to tweak the code directly and then use in Unity, so we should still go forward with your PR. Thanks again!

**Comment by ThomasBartanen** [comment]
Okaaaay, I see what happened then. Haha. I was thinking "I never saw a DLL file." But I guess I downloaded the source code. Past Thomas wanted to tweak it if needed, like you're saying.

Well, that's the beauty of open source, right? ANYONE can make mistakes with it, ha.

**Comment by caesuric** [comment]
All merged and release. Enjoy, and feel free to let me know if you have any other issues or requests!
