### ISSUE TITLE
Create a new Thread every time Update() ?

### ISSUE THREAD

**Issue by hoangcuongzk1** [caesuric/mountain-goap#30]
```cs
   /// <summary>Executes an asynchronous step of agent work.</summary>
    private void StepAsync()
    {
      if (!this.IsBusy && !this.IsPlanning)
      {
        this.IsPlanning = true;
        new Thread((ThreadStart) (() => Planner.Plan(this, this.CostMaximum, this.StepMaximum))).Start();
      }
      else
      {
        if (this.IsPlanning)
          return;
        this.Execute();
      }
    }
```
I'm not good at C# Unity, but I wonder if this code is bad for performance. Creating a new thread every time Update() is called sounds like a very bad idea. Could you explain this to me?

**Comment by caesuric** [comment]
Sure, if it's busy or planning, it won't start a new thread. Right before it starts the thread, it sets the flag that says it's planning to true. So it should never start more than one planning thread at once.

**Comment by hoangcuongzk1** [comment]
> Sure, if it's busy or planning, it won't start a new thread. Right before it starts the thread, it sets the flag that says it's planning to true. So it should never start more than one planning thread at once.

Anyway, this repository is perfect for me. It's very helpful for a GOAP beginner. Thank you so much! <3
